[project]
name = "stashup"
version = "0.1.0"
description = "日常帳務管理"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.116.1",
    "pydantic==2.11.7",
    "pydantic_core==2.33.2",
    "SQLAlchemy==2.0.41",
    "uvicorn==0.35.0"
]
